# -*- coding: utf-8 -*-
"""
Created on Sat Sep 19 17:25:29 2020

@author: uia76912
"""
##Library calling and program documentation

from random import randint
Players_turn = 0
play_the_game = 'y'

print("\n                Welcome to Number Guessing Challenge ")

print("\nIn this game, you are going to play with the computer")

print("\n\nWhat you need to is, guess a number between 0 to 100. In the meanwhile, computer will also guess a number")
print("If the difference between the number you guessed and what computer has guessed has a difference of:")
print("     -within 10 of the number, return 'WARM!'")
print("     -further than 10 away from the number, return 'COLD!'")

print("\nOn all subsequent turns, if a guess is")
print("     -closer to the number than the previous guess return 'WARMER!'")
print("     -farther from the number than the previous guess, return 'COLDER!'")

print("\n\nThe more quickly yo guess a right number, the better your thinking skills are!!")



## This function finds the difference between the human guessed number and the random number generated by 
##computer. This runs only during the first run. 

def first_turn(guessed_number, random_number):
    if abs(guessed_number - random_number) < 10:
        return("Warm", abs(guessed_number - random_number) )
    else:
        return("Cold", abs(guessed_number - random_number))
        
## This function runs during the subsequent runs. 

def subsequent_turn(guessed_number, random_number, diference):
    if abs(guessed_number - random_number) < difference:
        return("Warmer", abs(guessed_number - random_number))
    else:
        return("Colder", abs(guessed_number - random_number))
        
## Program Logic
while play_the_game =='y':
    
#Generate the randome numbers
    if Players_turn == 0:
        random_number = randint(1,100)
        #print("random number is:", random_number)
        difference = 0

#Ask the user to enter a number of thier choice
    Players_turn += 1
    guessed_number = int(input("\nPlease enter a number of your choice :"))
    
#Dont allow the user to enter a number beyond 0 and 100    
    if guessed_number < 0 or guessed_number > 100:        
        print("Out of Bounds")
        
#If the guessed number is correct, then ask if the user wants to still continue with the game. 
    elif guessed_number == random_number:
        print("Guessed Number is equal to Random Number")
        print("Number of turns :", Players_turn )
        try_again = input("\nDo you want to try once more(y/n):" )
        if try_again == 'y':
            Players_turn = 0
        else:
            play_the_game ='n'
            print("Game is over. Bye!!!")
            
#This loop called during the first turn only.         
            
    elif Players_turn == 1:
        Climate_Condition, difference = first_turn(guessed_number, random_number)
        print(Climate_Condition)
        
#This turn will be called during all the subsequent turns        
    elif Players_turn > 1:
        Climate_Condition, difference = subsequent_turn(guessed_number, random_number,difference)
        print(Climate_Condition)
        

        
          
